# Deliverable 1. Retrieve Weather Data.
---
1. Create a folder called `Weather_Database` to save all the files related with this deliverable.

2. Save the `Weather_Database_starter_code.ipynb` starter code to the `Weather_Database` folder and rename it as `Weather_Database.ipynb`.

3. Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

4. Use the `citipy` module to get the nearest city for each latitude and longitude combination.

5. Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key; also, it's critical to avoid publishing your API key on your GitHub repository.

6. Retrieve the following information from the API call:

    * Latitude and longitude

    * Maximum temperature

    * Percent humidity

    * Percent cloudiness

    * Wind speed

    * Weather description (for example, clouds, fog, light rain, clear sky)

7. Add the weather data to a new DataFrame.

8. Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.
---

In [10]:
# Import initial libraries
import numpy as np
import pandas as pd
from citipy import citipy

## Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

In [23]:
# Create a set of random latitude and longitude combinations
lats = np.random.uniform(low=-90.000,high=90.000, size=2000)
lngs = np.random.uniform(low=180.000,high=180.000, size=2000)

# Use the zip function to create an iterator of tuples containing the latitude and longitude combinations
lat_lngs = zip(lats,lngs)
lat_lngs

In [24]:
# Add the latitudes and longitudes to a list
coordinates = list(lat_lngs)

## Use the `citipy` module to get the nearest city for each latitude and longitude combination.

In [25]:
# Create an empty list for holding the cities
cities = []

# Use a for loop to identify nearest city for each latitude and longitude combination using the citipy module
for coordinate in coordinates:
    # Use the citipy module to identify the nearest city to the current coordinate
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

20

## Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key.

In [26]:
# Import the requests library
import requests

# Import the time library
import time

# Import the datetime module from the datetime library
from datetime import datetime

# Import the OpenWeatherMap's API key
from config import weather_api_key

In [27]:
# Assemble the OpenWeatherMap's API call
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID="+weather_api_key

## Retrieve the following information from the API call.

- The latitude and longitude
- The Max temperature
- The % humidity
- The % cloudiness
- The Wind speed
- The Weather description, i.e., cloudy, fog, light rain, clear sky, etc.

In [50]:
# Create an empty list to hold weather data for each city
city_data = []

# Print a message to indicate that the data retrieval starts
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters and set them to 1
record_count = 1
set_count = 1

# Loop through all the cities in our list to fetch weather data for each city
for i, city in enumerate(cities):
        
    # Group cities in sets of 50 for logging purposes
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create an endpoint URL for each city
    city_url = url + "&q=" + city.replace(" ","+")
    
    # Log the url, record, and set numbers
    print(f"Processing Record {record_count} of Set {set_count} | {city}")

    # Add 1 to the record count
    record_count += 1

    # Run an API request for each of the cities
    try:
        city_weather = requests.get(city_url).json()
        # Parse out the latitude, longitude, max temp, humidity, cloudiness, wind, country, and weather description
        
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_maxTemp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_weather = city_weather["weather"][0]["description"]
       
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Latitude": city_lat,
                          "Longitude": city_lng,
                          "Maximum Temperature": city_maxTemp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Current Description": city_weather})
        
    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass

# Indicate that the data retrieval is complete 
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | rungata
City not found. Skipping...
Processing Record 2 of Set 1 | ruatoria
City not found. Skipping...
Processing Record 3 of Set 1 | nikolskoye
Processing Record 4 of Set 1 | leningradskiy
Processing Record 5 of Set 1 | butaritari
Processing Record 6 of Set 1 | kaitangata
Processing Record 7 of Set 1 | beringovskiy
Processing Record 8 of Set 1 | dunedin
Processing Record 9 of Set 1 | waipawa
Processing Record 10 of Set 1 | russell
Processing Record 11 of Set 1 | tolaga bay
Processing Record 12 of Set 1 | asau
Processing Record 13 of Set 1 | christchurch
Processing Record 14 of Set 1 | isangel
Processing Record 15 of Set 1 | ngunguru
Processing Record 16 of Set 1 | gisborne
Processing Record 17 of Set 1 | rawannawi
City not found. Skipping...
Processing Record 18 of Set 1 | otane
Processing Record 19 of Set 1 | hastings
Processing Record 20 of Set 1 | anadyr
-----------------------------
Data Retrieval Complete
-----------------------------

In [51]:
# Print the length of the city_data list to verify how many cities you have
len(city_data)

17

## Add the weather data to a new DataFrame.

In [52]:
# Use the city_data list to create a new pandas DataFrame.
city_data_df = pd.DataFrame(city_data)

In [53]:
# Display sample data
city_data_df.head(10)

,City,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Country,Current Description
0,Nikolskoye,59.7035,30.7861,26.49,93,100,5.37,RU,light snow
1,Leningradskiy,69.3833,178.4167,-23.93,97,100,12.71,RU,overcast clouds
2,Butaritari,3.0707,172.7902,80.74,74,100,10.18,KI,overcast clouds
3,Kaitangata,-46.2817,169.8464,66.16,67,100,6.02,NZ,overcast clouds
4,Beringovskiy,63.0500,179.3167,-14.87,92,27,12.24,RU,scattered clouds
5,Dunedin,-45.8742,170.5036,59.81,95,100,12.30,NZ,overcast clouds
6,Waipawa,-41.4122,175.5153,70.36,57,16,17.07,NZ,few clouds
7,Russell,32.3502,-85.1999,68.00,94,0,5.75,US,clear sky
8,Tolaga Bay,-38.3667,178.3000,67.68,71,48,13.69,NZ,scattered clouds
9,Asau,46.4333,26.4000,29.32,76,44,7.16,RO,scattered clouds

In [54]:
# Display the DataFrame's column names using the columns Pandas function
city_data_df.columns

Index(['City', 'Latitude', 'Longitude', 'Maximum Temperature', 'Humidity',
       'Cloudiness', 'Wind Speed', 'Country', 'Current Description'],
      dtype='object')

In [57]:
# Create a list to reorder the column names as follows:
# "City", "Country", "Lat", "Lng", "Max Temp", "Humidity",  "Cloudiness", "Wind Speed",  "Current Description"
cols = city_data_df.columns.tolist()
#cols
# Recreate the DataFrame by using the new column order
city_data_df=city_data_df[["City", "Country", "Latitude", "Longitude", "Maximum Temperature", "Humidity",  "Cloudiness", "Wind Speed",  "Current Description"]]
# Display sample data
city_data_df.head(10)

,City,Country,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Current Description
0,Nikolskoye,RU,59.7035,30.7861,26.49,93,100,5.37,light snow
1,Leningradskiy,RU,69.3833,178.4167,-23.93,97,100,12.71,overcast clouds
2,Butaritari,KI,3.0707,172.7902,80.74,74,100,10.18,overcast clouds
3,Kaitangata,NZ,-46.2817,169.8464,66.16,67,100,6.02,overcast clouds
4,Beringovskiy,RU,63.0500,179.3167,-14.87,92,27,12.24,scattered clouds
5,Dunedin,NZ,-45.8742,170.5036,59.81,95,100,12.30,overcast clouds
6,Waipawa,NZ,-41.4122,175.5153,70.36,57,16,17.07,few clouds
7,Russell,US,32.3502,-85.1999,68.00,94,0,5.75,clear sky
8,Tolaga Bay,NZ,-38.3667,178.3000,67.68,71,48,13.69,scattered clouds
9,Asau,RO,46.4333,26.4000,29.32,76,44,7.16,scattered clouds

In [59]:
# Display the data types of each column by using the dtypes Pandas function
city_data_df.dtypes

City                    object
Country                 object
Latitude               float64
Longitude              float64
Maximum Temperature    float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
dtype: object

## Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.

In [60]:
# Set the output file name
fileName = "WeatherPy_Database"
# Export the city_data DataFrame into a CSV file
city_data_df.to_csv(fileName+".csv", sep=',', index=False)